spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  application:
    name: velog
  datasource:
    url: jdbc:mysql://localhost:3306/velogdb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23lijOlIWGypZ6YNUR
            client-secret: 5cf135ae39057a27bdb891d1039fd45569c7a9a9
            scope: read:user, user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            client-name: Github
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
      timeout: 30m